version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
  frontend:
    image: python:3.10
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port=8501
    depends_on:
      - backend
